import { Code, Flex, Heading, Link, Text } from '@chakra-ui/react';
import Head from 'next/head';
import { NextPage } from 'next/types';

const Home: NextPage = () => {
  return (
    <Flex flexDirection={'column'} minHeight={'full'}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex as={'main'} flexDirection={'column'} justifyContent={'center'} alignItems={'center'} flex={1}>
        <Heading as={'h1'}>
          Welcome to{' '}
          <Link textColor={'#0070f3'} href="https://nextjs.org">
            Next.js!
          </Link>
        </Heading>

        <Text>
          Get started by editing <Code>pages/index.tsx</Code>
        </Text>
      </Flex>

      <Flex as={'footer'} flexDir={'column'} alignItems={'center'} flex={1}></Flex>
    </Flex>
  );
};

export default Home;
